services:
  chat_app:
    build:
      context: .
      dockerfile: .sre/Dockerfile
    container_name: chat_app
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - local_network

networks:
  local_network:
    external: true
